---
- name: Copy docker-compose file
  hosts: docker
  tasks:
    - name: Créer un dossier
      file:
        path: /root/docker-compose
        state: directory
        mode: '0755'
    - name: Copier le fichier docker-compose.yml
      copy:
        src: files/docker-compose.yml
        dest: /root/docker-compose/docker-compose.yml
    - name: Launch docker docker-compose
      shell:
        "docker-compose up -d -f /root/docker-compose/docker-compose.yml"